### ISSUE TITLE
Specifying GNUPLOTTERMINAL="x11" in important_settings gives terminal qt in gnuplot files

### ISSUE THREAD

**Issue by pzeiger** [tdep-developers/tdep#11]
When I specify 
```
# Which gnuplot terminal to use by default.
GNUPLOTTERMINAL="x11" # other options are "aqua" and "x11"

```
in the file `important_settings`, the first line in `.gnuplot` files produced by TDEP reads
```
set terminal qt  size 500,350 enhanced font "CMU Serif,10"
```
So it does not respect my setting.

**Comment by flokno** [comment]
Yes, the mechanism actually works a bit different through precompiler flags: https://github.com/tdep-developers/tdep/blob/ac38d93c3e5e468d3160508264ff2ae04e219345/src/libolle/konstanter.f90#L142-L155

I fear there is no direct way to specify the terminal.

I recommend to run `phonon_dispersion_relations -p` which creates a `outfile.group_velocities.gnuplot_pdf` from which you can create a `outfile.dispersion_relations.pdf` and view it (that's what I do all the time anyways)
