### ISSUE TITLE
How to calculate the energy-dependent self energy from both three-phonon and four-phonon scattering?

### ISSUE THREAD

**Issue by chejunwei2** [tdep-developers/tdep#15]
Dear developer,
The lineshape section of manual shows " This code calculates the energy-dependent self energy from three-phonon scattering, as well as the contributions from mass imperfections and four-phonon scattering". But I didn't find any introduction on how to include the four-phonon scattering. Meanwhile, your paper entitled “Anharmonicity and ultralow thermal conductivity in lead-free halide double perovskites” also includes the contribution of the four-phonon scattering. So I wondered what command can be used to incorporate four-phonon scattering into self-energy calculation. Thank you very much.
Best regards,
Junwei Che

**Comment by flokno** [comment]
Hi @chejunwei2 ,

you can include fourth order scattering via `lineshape --fourthorder`. You can check with `--verbose` that it is included, you should get output like

```
...
 Calculating lineshapes for a single q-point
          liso: T
   lthirdorder: T
  lfourthorder: T
...
```

Please note that this will include the fourth-order terms **only in the real part of the self energy**, i.e., for the frequency shifts. **Linewidths/lifetimes will be unaffected!**

**Comment by chejunwei2** [comment]
Thank you very much for your reply.

**Comment by faridf** [comment]
Thanks for opening this issue. I wanted to know if there has been any update on performing lineshapes with fourthorder and also affecting Linewidths/lifetimes.
If there hasn't been an update on it, would you please recommend a method that I can calculate that? 

Thank you
