### ISSUE TITLE
Error: Message size bigger than supported by PSM2 API in MPI_Allreduce

### ISSUE THREAD

**Issue by NinaStrasser** [tdep-developers/tdep#23]
I encountered an error while running the following command: mpirun extract_forceconstants -rc2 7.0. The error message indicates that the message size is larger than what the PSM2 API can handle in an MPI_Allreduce operation. This results in MPI processes aborting, which cancels my job running on a cluster. I am trying to converge the cutoff value for the second order force constants for a system that has 328 atoms in the unit cell using 309 configurations from an MD trajectory in VASP. The calculations worked fine for the cutoffs of 5 and 6 Angstroms. 

Screenshot:
![PSM2_API_ERROR](https://github.com/tdep-developers/tdep/assets/110546708/44b702af-a320-4b51-9323-c2526e57c1ce)

Can you provide any recommendations for resolving this error when dealing with larger cutoff values?

**Comment by flokno** [comment]
Hi @NinaStrasser , can you add the full logfile?

I can only guess that you're trying to fit a gazillian force constants when your unit cell has 328 atoms and your cutoff is 7AA. Please try with `-rc2 0` first, this will use the nearest neighbor distance. Maybe this will at least yield something.

**Comment by flokno** [comment]
One thing you can try is to use `-nj2` instead of `-rc2`. If that helps you in any way we can talk about what that means. You will need larger numbers, always look for the number of force constants you get

**Comment by NinaStrasser** [comment]
I have 1118 force constants for 5AA and 1916 force constants for 6AA

**Comment by NinaStrasser** [comment]
Hi @flokno, I have now performed the calculations with different -nj2 settings, however, it did not resolve the issue. 
![Extract_FCs_nj2](https://github.com/tdep-developers/tdep/assets/110546708/c69e9d86-03e2-4f3c-aea4-be5156aa5686)
The same error is reproduced, when I use -nj2 200 that results in 3489 second order force constants. I have also attached the log file.
[fc2.log](https://github.com/tdep-developers/tdep/files/12999854/fc2.log)
Do you have any other suggestions?

**Comment by flokno** [comment]
Hi @NinaStrasser the actual number of force constants is the second number, i.e., 30750 in this output file. That is really quite a lot, much larger than what TDEP is designed for so to be honest I am suprised that you can push it this far in the first place. Also you would need way more samples to fit this properly, when you look for `REPORT GRADE OF OVERDETERMINATION`, that is just ~10. This should rather be in the hundreds.

May I ask what structure you are looking at? Why do you have 328 atoms in the unit cell? This is larger than I have seen people using for amorphous systems

**Comment by NinaStrasser** [comment]
Thanks for your explanation! Our group is mainly interested in metal-organic frameworks that often consist of hundreds of atoms in the primitive unit cell. However, in this particular case I wanted to simulate a rather complex Zn coordination polymer.

**Comment by NinaStrasser** [comment]
Hi @flokno! I have now updated the table with the actual numbers of force constants.
![TDEP_Table_1](https://github.com/tdep-developers/tdep/assets/110546708/acda9661-6252-4c8a-b89d-2136caf0d4e4)

Here is the second table including the convergence tests of the realspace cutoff. I also included the overdetermination ratio. 
![TDEP_Table_2](https://github.com/tdep-developers/tdep/assets/110546708/84761b3f-37a0-46a3-ab21-e7993ed90a3d)

Computations involving cutoffs of 6 AA and 6.5 AA will not result in the MPI error message, but did not finish within almost 24 h.
