### ISSUE TITLE
[ERROR] Fourth Order Nullspace Errors

### ISSUE THREAD

**Issue by ejmeitz** [tdep-developers/tdep#27]
Hello,

I was using the extract_forceconstants command to find 2nd 3rd and 4th order force constants. This command works fine for me to calculate 2nd and 3rd order; however, when I tried adding 4th order things crashed and I am unsure why. This is not the easiest thing to debug for me since it took 5 days before the error was thrown. Specifically the errors come when trying to find the null-space of the fourth order LSQ problem. I might not have enough samples to be over-determined at 4th order but I didn't get any useful errors and its hard to re-run and check so any help would be appreciated.

**Simulation Params:**
FCC LJ, 256 Atoms, 200 configurations sampled from MD 5 ps apart.

**Command:**
`mpirun -np 40 extract_forceconstants -rc2 8.5 -rc3 8.5 -rc4 8.5 --potential_energy_differences
`

**The last correct output from TDEP:**
```
     ... and 123 more shells
 ... determined singlet nullspace
 ... determined pair nullspace
 ... determined triplet nullspace
```

**The error messages are:**

>  ERROR
>  exit code 4: symmetry error
> 
>  Not as invariant as it should be.
> 
>   occurs in file: lo_symmetry_of_interactions_nullspace.f90
>   occurs on line: 477
>   active rank: 8 out of 40
> 

> Error termination. Backtrace:
> Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
> ERROR STOP 4

**Input Files:**
[TDEP_Input.zip](https://github.com/tdep-developers/tdep/files/13239340/TDEP_Input.zip)

**Comment by flokno** [comment]
Hi @ejmeitz , can you add the full log of `extract_forceconstants`?

**Comment by ejmeitz** [comment]
The program did not make a log file. What would it be called? I'm using a version of TDEP from before it was public.

**Comment by flokno** [comment]
Hi, please follow the basic tdep tutorials to learn what to look for: 

https://github.com/tdep-developers/tdep-tutorials/tree/main/01_basics

as a general hint: your force constant cutoffs are likely _way_ too big

there are convergence tutorials as well:

https://github.com/tdep-developers/tdep-tutorials/tree/main/02_sampling/convergence

**Comment by ejmeitz** [comment]
Using nearest neighbor for fourth order got past the error. Would you consider adding an error message that just stops the program if your system is way underdetermined?

**Comment by flokno** [comment]
All parameters need to be explicitly converged, as documented. Giving general rules of thumb is unfortunately not possible.
