### ISSUE TITLE
Error during the compilation

### ISSUE THREAD

**Issue by arpitem** [tdep-developers/tdep#32]
In order to help you with a problem, we need to know what happened. 

I am trying to install the TDEP on hpc supercomputer. I have tried different compilers, different version of modules etc. and I keep running in some error.

Therefore, please provide the following:

**- [ ] Describe the error message you encountered.**
lo_memtracker.f90(6): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MPI]
use mpi
----^
lo_memtracker.f90(186): error #6404: This name does not have a type, and must have an explicit type.   [MPI_IN_PLACE]
        call mpi_allreduce(MPI_IN_PLACE,j,1,MPI_INTEGER,MPI_SUM,comm,k)
---------------------------^
lo_memtracker.f90(186): error #6404: This name does not have a type, and must have an explicit type.   [MPI_INTEGER]
        call mpi_allreduce(MPI_IN_PLACE,j,1,MPI_INTEGER,MPI_SUM,comm,k)
--------------------------------------------^
lo_memtracker.f90(186): error #6404: This name does not have a type, and must have an explicit type.   [MPI_SUM]
        call mpi_allreduce(MPI_IN_PLACE,j,1,MPI_INTEGER,MPI_SUM,comm,k)
--------------------------------------------------------^
lo_memtracker.f90(210): error #6404: This name does not have a type, and must have an explicit type.   [MPI_MAX]
            call mpi_allreduce(MPI_IN_PLACE,j,1,MPI_INTEGER,MPI_MAX,comm,k)
------------------------------------------------------------^
compilation aborted for lo_memtracker.f90 (code 1)
make: *** [Makefile:196: ../../build/libolle/lo_memtracker.o] Error 1

**- [ ] Provide the **full** command you were running**

The intel module is already loaded.

module load hdf5-serial/1.14.0 (to load hdf5)

cp important_settings.sigma important_settings
bash build_things.sh

module list:
Currently Loaded Modules:
  1) intel-classic/2021.6.0-magic   2) mvapich2/2.3.7   3) jobutils/1.0   4) texlive/20220321   5) StdEnv (S)   6) hdf5-serial/1.14.0

  **- [ ] If you are using a script to run or submit the command, please provide this as well**
 The above script is same as in the getup repository. I tried changing compiler as well

I believe it is system related problem and I need to provide paths of mph correctly but I am stuck on how to proceed further. If anyone has any idea how I can resolve this, please let me know. Thank you for all the help and sharing the code.

**Comment by flokno** [comment]
Hi @arpitem , happy new year!

You must definitely adjust the INCLUDE paths in your `important_settings`, in particular `PATH_TO_MPI_LIB`, see [installation instructions](https://github.com/tdep-developers/tdep/blob/main/INSTALL.md#example).
