### ISSUE TITLE
[ERROR] Born effective charge not Hermitian

### ISSUE THREAD

**Issue by kli103** [tdep-developers/tdep#33]
Hi,

I was trying to include LOTO to phonon in extract_forceconstant. The symmetry of the material I am studying is low, and the Born effective charge tensor is not symmetryic. TDEP showed the following error:
 ... Born charges not Hermitian, error:   8.2344767095669359E-007
 ... DISPERSIONS MIGHT BE IRREGULAR!
 ... FIXME!

This error causes incorrect phonon dispersion.

But some previous discussion indicates that the Born effective charge needs not be Hermitian. http://www.democritos.it/pipermail/pw_forum/2006-January/003511.html

Could you resolve this issue? The log files can be found in the zip file attached.
[extract_forceconstants_rc5_skip_400_loto.zip](https://github.com/tdep-developers/tdep/files/13639893/extract_forceconstants_rc5_skip_400_loto.zip)

**Comment by flokno** [comment]
Hi @kli103 ,

right now, the only reliable workaround is to use `tdep_simplify_bec` from https://github.com/flokno/tools.tdep via

```
tdep_simplify_bec infile.lotosplitting
```

and use the resulting `outfile.lotosplitting`. This will symmetrize the BEC and make them effectively scalar. Unfortunately there is currently no better solution.
