### ISSUE TITLE
Evaluate & Save System Energy from Force Constants

### ISSUE THREAD

**Issue by ejmeitz** [tdep-developers/tdep#37]
Is it possible to enable a clean way to get the system energy evaluated within TDEP inside the `extract_forceconstants` command? I think this would be useful for assessing convergence of the force constants as the energy is what was used in the [TDEP 3rd order paper](https://arxiv.org/abs/1308.5436) to demonstrate convergence. Right now the energy is printed to the console or into the log file but that is not the easiest thing to parse and nearly impossible if you used MPI.  Maybe I'm missing an alternate way to get this from TDEP if so please let me know! I do have my own code for this but it would be nice if to check convergence all I needed was TDEP and some basic python scripts. Thanks!

**Comment by flokno** [comment]
Do you mean the final model energy (for all samples) or the energy _per sample_?

**Comment by flokno** [comment]
Yes, it is calculated. With `--verbose` you even get an output for some of the samples now. Using this flag or adding one to dump the energies to, say `outfile.energies` would be straightforward

**Comment by flokno** [comment]
I had one more look: The output from `--verbose` is broken for all-electron energies (like from FHI-aims), which is already fixed in my somewhat larger developer branch https://github.com/tdep-developers/tdep/pull/16 . Maybe dumping all energies could be included there, since it already does the same thing for pressure (write pressure and stress per time step to file)

**Comment by ejmeitz** [comment]
> Using this flag or adding one to dump the energies to, say `outfile.energies` would be straightforward

This would be perfect! If you do add it to one of the dev branches please let me know, I'd love to use it.

**Comment by flokno** [comment]
No, it only prints s limited number of samples since the full list of samples can be in the thousands for the case of MD (which was the dominant way of sampling at the time)

**Comment by flokno** [comment]
Ok I added this in #38 . @ejmeitz please check that this is what you want and please double check if it is correct also. Note the unit which is given in meV/atom where no. of atoms is the no. of atoms in the supercell. That should be the same unit we use for the other output, also it is written to the header of the `outfile.energies`. That file should be as easy to read as `np.loadtxt(...)`

**Comment by ejmeitz** [comment]
> Ok I added this in #38

I will test it this afternoon, thank you very much! 

As a side note would you expect thousands of samples to be required for MD with an empirical potential (e.g SW silicon)? I was under the impression a couple hundred was usually enough, although like I said I have not checked my convergence.

**Comment by flokno** [comment]
> As a side note would you expect thousands of samples to be required for MD with an empirical potential (e.g SW silicon)? I was under the impression a couple hundred was usually enough, although like I said I have not checked my convergence.

"enough" is a highly problem-specific word: https://github.com/tdep-developers/tdep-tutorials/tree/main/02_sampling/convergence

**Comment by ejmeitz** [comment]
@flokno this output looks perfect! Just to confirm `E_pot` is the value from my simulation (looks like it matches my `dump.stat`) and adding the other four columns together gives the energy prediction from the taylor series using the force constants calculated by TDEP?

**Comment by flokno** [comment]
> @flokno this output looks perfect! Just to confirm `E_pot` is the value from my simulation (looks like it matches my `dump.stat`) and adding the other four columns (plus U0??) together gives the energy prediction from the taylor series using the force constants calculated by TDEP?

Yes, this should be the case.

> Edit: Nothing quite seems to make the energies add up to the MD energy I have. But the R^2 is 0.97

Don't forget the baseline energy (`U0`).

**Comment by flokno** [comment]
I checked and it seems work for me:

![grafik](https://github.com/tdep-developers/tdep/assets/28858706/aed25586-0421-47f9-a564-11746775b2e9)

Things to note:
- The energy in `infile.stat` is in eV it needs to be scaled with the number of atoms in the supercell.
- If you use polar corrections, don't forget to add `Epolar`
- The baseline energy `U0` is in eV/atom, not meV. I guess to be consistent it would be better to write the other energies in eV/atom as well, I have changed that in https://github.com/tdep-developers/tdep/pull/38/commits/9b93ac79596b999da74dbb17df2df4f8b411bfb2

Does it work for you now?

**Comment by ejmeitz** [comment]
Yeah was a silly mistake I forgot to multiply the `U0` by 1000. This looks good to me now.

While I have you here, what are the other numbers dumped in the `energies.U0` file? My file has:
` -0.415895270894E+01 -0.433074957112E+01 -0.432766705602E+01 -0.432766705602E+01`
but based on the log info one of the last 2 is U0 I'm looking for.

**Comment by flokno** [comment]
Yes I see the problem. I made this more expliclity in https://github.com/tdep-developers/tdep/commit/9b93ac79596b999da74dbb17df2df4f8b411bfb2 as well. The output is now self-explanatory:

```
# Unit:      eV/atom
# no. atoms: 216
#            mean(Epot)                     mean(Epot - Epolar - E2)       mean(Epot - Epolar - E2 - E3)  mean(Epot - Epolar - E2 - E3 - E4)
            -0.273141372188E+05            -0.273141886234E+05            -0.273141886234E+05            -0.273141886234E+05
            ```

**Comment by ejmeitz** [comment]
Ah makes sense, thanks for clarifying. I'm happy with this addition and think this issue can be closed if you feel it is done.

**Comment by ejmeitz** [comment]
@flokno did you change something in the PR? I re-pulled the code this morning and now the energies in `outfile.energies` only matches what is in the log file. For example, with `--stride 1` the `outfile.energies` only has. Earlier when the units were different and the U0 file was missing a header things seemed fine.

> # Unit:      eV/atom
> # no. atoms: 216
> #  conf    Epot                  Epolar                Epair                 Etriplet              Equartet
>     20   -0.414904816227E+01    0.000000000000E+00    0.179850425066E+00   -0.274698346872E-02    0.000000000000E+00
>     40   -0.416118689888E+01    0.000000000000E+00    0.165627782869E+00   -0.141429135960E-02    0.000000000000E+00
>     60   -0.416980478422E+01    0.000000000000E+00    0.160519373511E+00   -0.242219492685E-02    0.000000000000E+00
>     80   -0.415694992378E+01    0.000000000000E+00    0.175664797109E+00   -0.214288939788E-02    0.000000000000E+00
>    100   -0.416527455270E+01    0.000000000000E+00    0.163339427548E+00   -0.985006163268E-03    0.000000000000E+00
>

**Comment by flokno** [comment]
The way this should work:

- When using `stride`, only the given subset of snapshots is read, everything else is ignored.
- On `stdout`, TDEP writes **at most** about ~20 of the energies evenly spaced over all samples.
- All energies from the simulation are written to `outfile.energies`.

Please check that this is indeed the case.

It is probably not the most obvious behavior, given that it's some semi-hidden feature, but one could add a hint in the `stdout` to reduce confusion.

**Comment by ejmeitz** [comment]
Right now the 'outfile.energies' does not have that behavior. With stride 1 only the samples from every 20 config that show up in logfile get put into outfile.energies. With stride 2 the configs from 20-100 with step 20 go to the outfile
and so on. I'm not sure what got changed, earlier with stride 1 every single configuration's energy was dumped.

**Comment by flokno** [comment]
Can you send me your input files? Maybe I have to few samples to trigger this behavior or sth.

**Comment by ejmeitz** [comment]
Yeah here's the input files. When testing the MWE I realized it only happens if I use MPI.

This command works:
`extract_forceconstants -rc2 3.77118 -rc3 3.77118 -s 1 --potential_energy_differences --verbose > tdep.log`
this does not:
`mpirun -np 20  extract_forceconstants -rc2 3.77118 -rc3 3.77118 -s 1 --potential_energy_differences --verbose > tdep.log`

[TDEP_MWE.zip](https://github.com/tdep-developers/tdep/files/14010865/TDEP_MWE.zip)

**Comment by flokno** [comment]
Right, MPI.

Can you check again?

**Comment by ejmeitz** [comment]
Yep looks good now. Thanks!

**Comment by flokno** [comment]
Alright, thanks for checking!

:shipit:
