### ISSUE TITLE
An error occurred in MPI_Pack

### ISSUE THREAD

**Issue by tingguangli** [tdep-developers/tdep#42]
I got an MPI error when I was trying to get phonon dos calculation:
Here is my following command:
phonon_dispersion_relations --dos
 
 Calculating phonon dispersions on a q-point path
 ... getting standard q-path
 ... interpolating points for path
 ... getting small group for each q-point
 ... building axis for plots
 ... setting ticks
 ... calculating frequencies             100.0% |========================================|  75.01842s
 Calculated dispersion on path in 75.01846s
 
  Settings: 
       mode Gruneisen parameters:  F
                 number of bands: 192
                 number of paths: 5
   number of points on each path: 100
 
         path 1: from GM to X
   starting point: cartesian 0.000000  0.000000  0.000000 fractional 0.000000  0.000000  0.000000 
     ending point: cartesian-0.000000  0.000000  0.029756 fractional 0.000000  0.000000  0.500000 
         path 2: from X to M
   starting point: cartesian-0.000000  0.000000  0.029756 fractional 0.000000  0.000000  0.500000 
     ending point: cartesian-0.000000  0.029756  0.029756 fractional 0.000000  0.500000  0.500000 
         path 3: from M to GM
   starting point: cartesian-0.000000  0.029756  0.029756 fractional 0.000000  0.500000  0.500000 
     ending point: cartesian 0.000000  0.000000  0.000000 fractional 0.000000  0.000000  0.000000 
         path 4: from GM to R
   starting point: cartesian 0.000000  0.000000  0.000000 fractional 0.000000  0.000000  0.000000 
     ending point: cartesian 0.029756  0.029756  0.029756 fractional 0.500000  0.500000  0.500000 
         path 5: from R to M
   starting point: cartesian 0.029756  0.029756  0.029756 fractional 0.500000  0.500000  0.500000 
     ending point: cartesian 0.029756  0.029756 -0.000000 fractional 0.500000  0.500000  0.000000 
  
 ...            got the phonon bandstructure in 75.018585117s
 FIXME: Large unitcell with           64  atoms used
 FIXME: Raman activity will NOT be reported
 
 Determining activity
 ... not Raman active
 ... IR active
 ... transformed IR coefficient
 ... found            3  active q-points
 ... found            0  Raman active modes
 ... found            6  IR active modes
 ... activity written to outfile.mode_activity.csv
  
 Calculating phonon dispersion across the Brillouin zone
 
 Calculating full dispersion relations over 1 MPI ranks
  ... irreducible dispersions            100.0% |========================================|  73.12753s
[phy-grads19:145087] *** An error occurred in MPI_Pack
[phy-grads19:145087] *** reported by process [2058223617,0]
[phy-grads19:145087] *** on communicator MPI_COMM_WORLD
[phy-grads19:145087] *** MPI_ERR_TRUNCATE: message truncated
[phy-grads19:145087] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[phy-grads19:145087] ***    and potentially your MPI job)
The last five lines are the ones that cause the issues for the MPI error of TDEP.

I also uploaded all of my input files for this calculation.
[tdep_input.zip](https://github.com/tdep-developers/tdep/files/14348486/tdep_input.zip)

**Comment by flokno** [comment]
Hi,

this is likely a memory error because the default q-point grid is too dense for your large unit cell.

Please try something like

```bash
phonon_dispersion_relations -p --dos -qg 5 5 5
```

and work your way up from there. You will likely hit a glass wall for sth like 15x15x15 grids, but maybe your DOS is long converged before that.

Please also consider to use `mpirun` for parallel runs.

**Comment by tingguangli** [comment]
Hi Florian,

Thanks for this clear explanation, it works well now!

Best Regards,
Tingguang
