### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred when using extract force constants

### ISSUE THREAD

**Issue by davy12344** [tdep-developers/tdep#45]
Hi, developers. I compile the code with intel compiler(With OneAPI). There is no error during the compiling process.  However, when I run the extract_forceconstants in example_1, it gives:

 ... reading unitcell
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libpthread-2.28.s  0000154CA92BACF0  Unknown               Unknown  Unknown
extract_forcecons  00000000007974F6  type_symmetryoper         658  type_symmetryoperation.f90
extract_forcecons  000000000078BD99  type_symmetryoper         490  type_symmetryoperation.f90
extract_forcecons  00000000005B7521  type_crystalstruc          62  type_crystalstructure_symmetry.f90
extract_forcecons  0000000000413993  MAIN__                     42  main.f90
extract_forcecons  000000000040F40D  Unknown               Unknown  Unknown
libc-2.28.so       0000154CA8F1DD85  __libc_start_main     Unknown  Unknown
extract_forcecons  000000000040F32E  Unknown               Unknown  Unknown

I also use gdb to check where problems happen. It tells me

 **Program received signal SIGSEGV, Segmentation fault.
0x00000000007974f6 in type_symmetryoperation::check_operation (op=..., tr=..., sbox=<error reading variable: Cannot access memory at address 0x0>, basis=..., fmap=..., valid=.FALSE.,
    tolerance=0.0001) at type_symmetryoperation.f90:845
845                allocate(dum(3,sbox(sp)%n))**

Is it possible that the process of compilation still has problem? I do not know how to optimize my import_setting now. Looking forward to your great suggestions:

Here is my import_setting file:
!#!/bin/bash
PYTHONHEADER="#!/bin/env python"
! Which gnuplot terminal to use by default.
GNUPLOTTERMINAL="x11" # other options are "aqua" and "x11"
!# the fortran compiler
FORTRAN_COMPILER="ifort"
OPTIMIZATION_LEVEL="-O0 -xHost -g -traceback" # first time you try you might want to put this to -O0 to make things compile a little faster.
!#OPTIMIZATION_LEVEL="-O0 -check bounds -check uninit -check pointers -check stack -traceback -g -fpe0 -init=snan,arrays -warn all -warn stderrors -stand f08 -diag-disable 5268"
! Extra options for the compiler to make it play nice
FCFLAGS="-cpp -gen-interfaces -fPIC"
!# flag that specifies location of modules
MODULE_FLAG="-module"
! Precompiler flags. Selecting default gnuplot terminal, and makes the progressbars work.
PRECOMPILER_FLAGS="-DGP${GNUPLOTTERMINAL} -Dclusterprogressbar"
!# you need BLAS and LAPACK
PATH_TO_BLASLAPACK_LIB="-L${MKL_ROOT}/lib/intel64"
PATH_TO_BLASLAPACK_INC="-I${MKL_ROOT}/include"
BLASLAPACK_LIBS="-qmkl=cluster"
!# I need the fftw library
PATH_TO_FFTW_LIB="-L/home/yonghengli/software/peturbe/tdep-24.01/fftw-3.3.10/build/lib"
PATH_TO_FFTW_INC="-I/home/yonghengli/software/peturbe/tdep-24.01/fftw-3.3.10/build/include"
FFTW_LIBS="-lfftw3"
!# Also need MPI
！#mpipath=/opt/gengzi/pub/toolkits/intel/oneapi/mpi/2021.10.0/intel64/
mpipath=/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/
PATH_TO_MPI_LIB="-L${mpipath}/lib"
PATH_TO_MPI_INC="-I${mpipath}/include"
MPI_LIBS="-lmpifort"
！# And a c-compiler
C_COMPILER="icc"
!# And HDF5
HDF5_DIR=/home/yonghengli/software/peturbe/hdf5/hdfsrc/build/
PATH_TO_HDF5_LIB="-L${HDF5_DIR}/lib"
PATH_TO_HDF5_INC="-I${HDF5_DIR}/include"
HDF5_LIBS="-lhdf5 -lhdf5_fortran"

**Comment by flokno** [comment]
Hi, unfortunately it is not possible to say anything without input and output files.

**Comment by davy12344** [comment]
Hi, developers, 
Thank you for your reply.
I tried gfortran. It seems to be the problem with intel compiler-2023(One-API). 
Best regards;
Yongheng Li
