### ISSUE TITLE
[ERROR]  exit code 4: symmetry error   Bad operation singlets

### ISSUE THREAD

**Issue by sgyang345** [tdep-developers/tdep#51]
**I got an error when I run the following command:**
_mpirun -np 44 extract_forceconstants -rc2 25_

 
**The detailed error output is as follows:**
 ERROR
 exit code 4: symmetry error

 Bad operation singlets

occurs in file: lo_symmetry_of_interactions_nullspace.f90
occurs on line: 97
active rank: 0 out of 1
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP 4

Error termination. Backtrace:
#0  0x55dd06b5349b in ???
#1  0x55dd06b3c905 in ???
#2  0x55dd06ae2c7a in ???
#3  0x55dd06a63e80 in ???
#4  0x55dd06a73661 in ???
#5  0x2ae0a2952554 in ???
#6  0x55dd06a60b68 in ???
...

**My calculation log is as follows:**
[fc.log](https://github.com/tdep-developers/tdep/files/14800873/fc.log)

**The number of atoms in my structure is more than 3000.**

**Comment by flokno** [comment]
I’m afraid we will never be able to run this large systems. Unit cells should be <≈ 100 and supercells <≈ 1000
