### ISSUE TITLE
Job killed “extract_forceconstants”

### ISSUE THREAD

**Issue by lshannnnn** [tdep-developers/tdep#52]
Hello, dear developer, I've been using your software for silicon testing and encountered an issue where my work frequently ends in an unexpected manner. This usually happens when executing the command "extract_forceconstants -rc2 5". Could you please advise on what might be causing this issue?

extract_forceconstants -rc2 5

 ... reading unitcell
 ... min cutoff: 2.37032
 ... max cutoff: 8.20277

 DETERMINING SYMMETRY OF INTERACTION TENSORS
 ... constructed distance tables (0.02471s)
 ... built singlets
 ... built pairs
 ... built prototype tuplets (0.00037s)
 ... expanded symmetry operations (0.16686s)
  ... reducing pairs                     100.0% |========================================|  0.00020s
  ... mapping pairs                      100.0% |========================================|  0.02164s
 N singlet shells:           1
          shell:  1   8
 N pair shells:           4
    shell:           1           8   0.0000000000000000
    shell:           2          32   2.3679512299170984
    shell:           3          96   3.8668481660618292
    shell:           4          96   4.5342813947351832
 ... determined singlet nullspace
 ... determined pair nullspace
 ... determined dielectric tensor nullspace
 ... determined Born charge nullspace
 Interactions:
        firstorder forceconstant:           0           0
       secondorder forceconstant:           4          10
        thirdorder forceconstant:           0           0
       fourthorder forceconstant:           0           0
             dielectric constant:           0           0
              dielectric singlet:           1           1
                 dielectric pair:           0           0
   born effective charge singlet:           0           0
      born effective charge pair:           0           0
   born effective charge triplet:           0           0

 GENERATING CONSTRAINTS
 ... 0 secondorder constraints (0.00142s)
 ... created 0 constraints (0.00146s)
 ... got constraints in 0.00147s

 READING SIMULATION FROM FILE
 ... made space and decided on heuristics
 ... reading simulation                  100.0% |========================================|  11.58603s
 ... got displacements
 ... short summary of simulation:
                       number of atoms: 216
              number of configurations: 19500
               average temperature (K): 299.71302
                 thermostat set to (K): 300.00000
                average pressure (GPa): 0.13303
   average stresstensor xx xy xz (GPa):       0.1377      -0.0035       0.0027
   average stresstensor yx yy yz (GPa):      -0.0035       0.1217       0.0122
   average stresstensor zx zy zz (GPa):       0.0027       0.0122       0.1397
 ... finished reading simulation (11.97897s)

 REPORT GRADE OF OVERDETERMINATION
     total number of equations:     12636000
      number of FC up 2. order:           10   --> overdetermination ratio:    1263600.0

 SOLVING FOR INTERACTION TENSORS
 ... distributed data
 ... no polar interactions to worry about
Killed

**Comment by flokno** [comment]
Please reduce the number of samples included in the fit, e.g., via the `--stride` option
