### ISSUE TITLE
[ERROR] rc2 cutoff convergence test

### ISSUE THREAD

**Issue by WenjiangZhou** [tdep-developers/tdep#55]
In order to help you with a problem, we need to know what happened. 

Therefore, please provide the following:

- [ ] I could not find a proper rc2 cutoff.
- [ ] ~/software/tdep-main/bin/extract_forceconstants -rc2 6 --polar.

Hello, TDEP developer,

I'm calculating the phonon band of a polar material. I think the rc2 cutoff is a critical parameter. I use different -rc2 and extract the phonon. However, this convergence test looks so strange. The results are below：

![捕获](https://github.com/tdep-developers/tdep/assets/50853739/25a1e07d-6218-4031-85e2-41a7249f8ed1)

In my view, the larger cutoff should give a good phonon, on the contrary. Note that my structure has 1024 atoms, and 50 structures in total.

**Comment by flokno** [comment]
@WenjiangZhou did you do DFT or use an interatomic potential?

**Comment by WenjiangZhou** [comment]
> @WenjiangZhou did you do DFT or use an interatomic potential?

I use DFT to train a potential, and obtain my temperature-dependence phonon based on this potential.

**Comment by flokno** [comment]
Please check that the realspace cutoff of the potential and make sure the TDEP cutoff is smaller. You are not fitting physical information beyond that cutoff, which explains the strange dispersions.

**Comment by WenjiangZhou** [comment]
> Please check that real space cutoff of the potential, and make sure the TDEP cutoff is smaller. You are not fitting physical information beyond that cutoff, which explains the strange dispersions.

OK, Thank you very much. My cutoff for the potential is 5 A. Mybe I think 5A gives a good phonon. Below is my phonon test for smaller cutoff.  

![image](https://github.com/tdep-developers/tdep/assets/50853739/5e5f5108-0ae5-4687-b3c0-63d9acd9b8ff)
