### ISSUE TITLE
[ERROR] No method to plot fat (projected) phonon dispersion

### ISSUE THREAD

**Issue by Seungwoo-Yoo** [tdep-developers/tdep#57]
First of all, I really appreciated to make this super nice program. It help me a lot when I do my work.

https://tdep-developers.github.io/tdep/program/phonon_dispersion_relations/
It show us that we can draw Fat(projected) phonon dispersion with this program, but I only can draw projected phonon dos, not projected phonon dispersion. Is there any method to draw fat phonon dispersion with this program?

Thank you so much.

**Comment by flokno** [comment]
Hi @Seungwoo-Yoo , thank you for your interest in TDEP.

This indeed possible, the information is saved in the `site_projection_per_mode` array in `outfile.dispersion_relations.hdf5`. The array has shape `(Nq, Nmodes, Natoms)` -- number of qpoints in your Brillouin zone path, number of modes, number of atoms in the unit cell.

Here's a small snippet how I plot the bandstructure for GaN separately for Ga and N, of course this can be done much nicer, but the idea should be clear:

```python
import numpy as np
import xarray as xr
from matplotlib import pyplot as plt

ds = xr.load_dataset("outfile.dispersion_relations.hdf5")

fig, axs = plt.subplots(nrows=2, sharex=True, figsize=(4, 6))

_x = ds.q_values.to_numpy()

for ii, iatom in enumerate([0, 2]):
    ax = axs[ii]
    for imode in range(12):
        q = _x
        y = ds.frequencies[:, imode]
        alpha = np.array(ds.site_projection_per_mode[:, imode, iatom])

        ax.scatter(q, y, alpha=alpha, color=f"C{ii}")
    ax.set_ylabel("Frequency (THz)")
    ax.set_title(f"Atom {iatom}")
ax.set_xlabel("q")
```

This produces the following plot for the bands resolved by Ga and N atoms:

![image](https://github.com/tdep-developers/tdep/assets/28858706/61c05a4b-b36a-42af-ae06-40f4d8302d0f)

**Comment by flokno** [comment]
For reference, the following matlab code snippet was used to create the projected plot on the webpage:

```matlab
%% plot phonon dispersions projected onto atoms

fn='/path/to/outfile.dispersion_relations.hdf5';
x=h5read(fn,'/q_values');
xtck=h5read(fn,'/q_ticks');
xtckl=strsplit(h5readatt(fn,'/','q_tick_labels'));
y=h5read(fn,'/frequencies');
frequnit=h5readatt(fn,'/frequencies','unit');
d=h5read(fn,'/site_projection_per_mode');
nmode=size(y,1);
for i=1:size(d,3)
for j=1:size(d,2)    
    z1(j,i)=d(1,j,i);% sum(d(1:1,j,i));
    z2(j,i)=sum(d(2:2,j,i));
end
end

figure(1); clf; hold on; box on;

colormap(lo_colormap4(100))


for i=1:nmode
    % ugly matlab trick to get varying colors along lines
    xi=x';
    yi=y(i,:);
    zi=yi*0;
    ci=z2(i,:);
    s=surface([xi;xi],[yi;yi],[zi;zi],[ci;ci]);
    set(s,'facecol','no','edgecol','interp','linew',2)
    %plot(x,y);
end

set(gca,'xtick',xtck,'xticklabel',xtckl,'yminortick','on','tickdir','out');

ylabel(['Frequency (' frequnit ')'])
xlim([0 max(x)])
ylim([0 ceil(max(max(y)))])

s=colorbar;
set(s,'TickDirection','out','Ticks',[0 1],'Ticklabels',{'Pb','Te'},'Limits',[0 1])
```
