### ISSUE TITLE
lineshape --readpath is not working

### ISSUE THREAD

**Issue by mayankaditya** [tdep-developers/tdep#62]
Hi,

I want to generate the phonon spectral function along a specific path in the BZ, so I modified the file.qpoints_dispersion and ran "lineshape --read path". I found that lineshape does not support the --readpath option, and only support the --path option (i.e. default TDEP directions). Please do needful.

Thanks,
Mayank

**Comment by flokno** [comment]
Please provide your input files and a script that contains the commands you used to run `lineshape`

**Comment by mayankaditya** [comment]
[TDEP.zip](https://github.com/tdep-developers/tdep/files/15231376/TDEP.zip)
Please see the attached input file. I ran the following command

lineshape --readpath, --temperature 300 --dumpgrid 


Thanks,
Mayank

**Comment by flokno** [comment]
By specifying `--dumpgrid`, you produce the spectral function on a q-point grid. You want it on a path, therefore you need to specify `--path`. Then `--readpath` will work, please find example plots from your data attached

![outfile phonon_spectral_function_path](https://github.com/tdep-developers/tdep/assets/28858706/f4b02a5d-d408-452f-8594-03e196a5a008)
![outfile phonon_spectral_function](https://github.com/tdep-developers/tdep/assets/28858706/d698ff80-a13c-47f5-bb68-d7e865bdb616)

**Comment by mayankaditya** [comment]
Thank You so much for your prompt response. Yes, its working now.

**Comment by flokno** [comment]
I also added an error message when conflicting options are passed to `lineshape` in https://github.com/tdep-developers/tdep/commit/9e897a5b77d7dae9736f52fb9e024ae239a2d939
