### ISSUE TITLE
ERROR:  the unique shells where perhaps not as unique as I thought.

### ISSUE THREAD

**Issue by chejunwei2** [tdep-developers/tdep#64]
Dear developer,
when I try to extract force constants using` extract_forceconstants -rc2 6`, I got the following errors:

 ... reading unitcell
 ... min cutoff: 3.62270
 ... max cutoff: 7.97860
 
 Building the tuplet symmetry table
 ... decided on the settings:
                  consider first order:  F
                   second order cutoff: 6.00000A
                    third order cutoff: -1.00000A
                   fourth order cutoff: -1.00000A
                        Polar material:  F
               use Wigner-Seitz cutoff:  F
               Wigner-Seitz dimensions:  -1 -1 -1
             check collinear magnetism:  F
         check non-collinear magnetism:  F
                  check transpositions:  T
                      check spacegroup:  T
       calculate magnetic interactions:  F
      cutoff for magnetic interactions: -1.00000A
     List of the number of neighbours included, per atom, for a specific cutoff:
       cutoff:   2.97293 min #    0  per atom:
  0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 2 2 2 2
       cutoff:   2.98605 min #    0  per atom:
  0 0 0 0 4 4 4 4 1 1 1 1 1 1 1 1 2 2 2 2
       cutoff:   2.99125 min #    0  per atom:
  0 0 0 0 6 6 6 6 2 2 2 2 2 2 2 2 2 2 2 2
       cutoff:   3.61908 min #    1  per atom:
  1 1 1 1 6 6 6 6 2 2 2 2 2 2 2 2 3 3 3 3
       cutoff:   3.62696 min #    3  per atom:
  3 3 3 3 6 6 6 6 3 3 3 3 3 3 3 3 3 3 3 3
       cutoff:   3.63782 min #    3  per atom:
  4 4 4 4 6 6 6 6 3 3 3 3 3 3 3 3 4 4 4 4
       cutoff:   3.85650 min #    4  per atom:
  6 6 6 6 6 6 6 6 4 4 4 4 4 4 4 4 4 4 4 4
       cutoff:   3.95015 min #    4  per atom:
  8 8 8 8 6 6 6 6 5 5 5 5 5 5 5 5 4 4 4 4
       cutoff:   4.16769 min #    4  per atom:
  8 8 8 8 6 6 6 6 7 7 7 7 7 7 7 7 4 4 4 4
       cutoff:   4.18349 min #    6  per atom:
  8 8 8 8 6 6 6 6 8 8 8 8 8 8 8 8 6 6 6 6
       cutoff:   4.20358 min #    6  per atom:
  8 8 8 8 6 6 6 6 9 9 9 9 9 9 9 9 8 8 8 8
       cutoff:   4.22369 min #    6  per atom:
  8 8 8 8 6 6 6 6 10 10 10 10 10 10 10 10 10 10 10 10
       cutoff:   4.25091 min #    6  per atom:
  8 8 8 8 6 6 6 6 11 11 11 11 11 11 11 11 12 12 12 12
       cutoff:   4.28467 min #    6  per atom:
  8 8 8 8 6 6 6 6 13 13 13 13 13 13 13 13 12 12 12 12
       cutoff:   4.45112 min #    6  per atom:
  9 9 9 9 6 6 6 6 13 13 13 13 13 13 13 13 13 13 13 13
       cutoff:   4.65957 min #    8  per atom:
  11 11 11 11 8 8 8 8 13 13 13 13 13 13 13 13 13 13 13 13
       cutoff:   4.70795 min #    8  per atom:
  11 11 11 11 8 8 8 8 14 14 14 14 14 14 14 14 13 13 13 13
       cutoff:   4.83349 min #   10  per atom:
  13 13 13 13 10 10 10 10 14 14 14 14 14 14 14 14 13 13 13 13
       cutoff:   4.92154 min #   10  per atom:
  14 14 14 14 10 10 10 10 14 14 14 14 14 14 14 14 14 14 14 14
       cutoff:   4.93309 min #   10  per atom:
  14 14 14 14 10 10 10 10 15 15 15 15 15 15 15 15 14 14 14 14
       cutoff:   5.05709 min #   10  per atom:
  14 14 14 14 10 10 10 10 15 15 15 15 15 15 15 15 16 16 16 16
       cutoff:   5.11303 min #   12  per atom:
  16 16 16 16 12 12 12 12 15 15 15 15 15 15 15 15 16 16 16 16
       cutoff:   5.23920 min #   12  per atom:
  18 18 18 18 12 12 12 12 16 16 16 16 16 16 16 16 16 16 16 16
       cutoff:   5.55863 min #   12  per atom:
  20 20 20 20 12 12 12 12 16 16 16 16 16 16 16 16 16 16 16 16
       cutoff:   5.59013 min #   14  per atom:
  22 22 22 22 14 14 14 14 16 16 16 16 16 16 16 16 16 16 16 16
       cutoff:   5.77840 min #   14  per atom:
  22 22 22 22 14 14 14 14 17 17 17 17 17 17 17 17 18 18 18 18
       cutoff:   5.79287 min #   17  per atom:
  22 22 22 22 18 18 18 18 17 17 17 17 17 17 17 17 18 18 18 18
       cutoff:   5.82595 min #   17  per atom:
  22 22 22 22 20 20 20 20 17 17 17 17 17 17 17 17 18 18 18 18
       cutoff:   5.83056 min #   18  per atom:
  22 22 22 22 22 22 22 22 18 18 18 18 18 18 18 18 18 18 18 18
       cutoff:   5.94577 min #   18  per atom:
  24 24 24 24 22 22 22 22 18 18 18 18 18 18 18 18 18 18 18 18
       cutoff:   5.94586 min #   18  per atom:
  24 24 24 24 22 22 22 22 18 18 18 18 18 18 18 18 20 20 20 20
       cutoff:   5.97209 min #   19  per atom:
  24 24 24 24 22 22 22 22 19 19 19 19 19 19 19 19 20 20 20 20
       cutoff:   5.98249 min #   20  per atom:
  24 24 24 24 22 22 22 22 20 20 20 20 20 20 20 20 20 20 20 20
 ... reducing pairs                     100.0% |========================================|  0.00058s 
 ... matching pair shells                 0.0% |                                        |  0.00003s
 ERROR:
  the unique shells where perhaps not as unique as I thought. Or something else
  went wrong.
  The vector I want to match:
  -6.880206       7.937414      0.0000000E+00
  These are the vectors I tried to match with:
           1  0.0000000E+00  0.0000000E+00  0.0000000E+00
           2  -1.437616       6.686259      0.0000000E+00
           3   2.640680      -4.275237       4.661090    
           4  -6.759656      -1.251154      0.0000000E+00
           5   4.239526       3.662177      -4.661090    
           6  -3.299213       2.129647      -6.348341    
           7   8.317822      -1.251154      0.0000000E+00
           8 -0.3292665       6.864619       5.504716    
           9   7.209472      -1.072795      -5.504716    
          10  -1.437616      -9.188568      0.0000000E+00
          11  -7.868005      -1.072795      -5.504716    
          12  -4.898059      -5.807766      -6.348341    
          13   6.880206      -7.937413      0.0000000E+00
          14   6.880206       7.937414      0.0000000E+00
          15 -0.3292665      -9.010208      -5.504716    
          16 -0.6585327      -2.145590      -11.00943    
          17  0.0000000E+00  0.0000000E+00  0.0000000E+00
          18   1.108349     -0.1783595      -5.504716    
          19  -4.568792      -3.202442     -0.8436255    
          20  -2.969946       4.734972     -0.8436255    
          21   7.538739      -7.937414      0.0000000E+00
          22  0.0000000E+00  0.0000000E+00   11.00943    
          23   10.50869      -3.202442     -0.8436255    
          24  0.0000000E+00  0.0000000E+00  0.0000000E+00
          25  -7.538739       1.532529      -1.687251    
          26   4.078296       4.913331       4.661090    
          27  -5.677142      -3.024083       4.661090    
          28  -3.460443      -3.380802      -6.348342    
          29   1.861597       4.556612      -6.348342    
          30  -1.598846       7.937413      0.0000000E+00
          31   5.939892      -6.404884      -1.687251    
          32  0.0000000E+00  0.0000000E+00   9.322181    
          33   9.400335      -3.024083       4.661090    
          34  -9.137585      -6.404884      -1.687251    
          35   5.939892       9.469942      -1.687251    
          36  0.0000000E+00  0.0000000E+00  0.0000000E+00
          37   8.317822      -1.251155      0.0000000E+00
          38  -5.322039       7.937413      0.0000000E+00
          39   2.216699     -0.3567192       11.00943    
  Future Olle will write some proper diagnostics for this.

My input file is 
[inputfile.zip](https://github.com/tdep-developers/tdep/files/15342676/inputfile.zip)
So I would like to ask for help. Thank you very much.

**Comment by johkl** [comment]
Hi,

Please make sure that your infile.ucposcar is properly symmetrized. You can find instructions on this in the tdep-tutorials repo: https://github.com/tdep-developers/tdep-tutorials/tree/main/00_preparation/refine_symmetry

Best,
Johan

**Comment by flokno** [comment]
Indeed I see spacegroup P(1) with the TDEP symmetry tolerance (see also https://github.com/tdep-developers/tdep?tab=readme-ov-file#symmetry-errors).

Fixing the symmetry should do the trick.

**Comment by chejunwei2** [comment]
Thank you very much for your help.
Best Regards
