### ISSUE TITLE
[phonon_dispersion_relations]  ERROR  exit code 4: symmetry error 

### ISSUE THREAD

**Issue by chewingram** [tdep-developers/tdep#68]
Hello, 
I'm trying to compute phonons of bulk MoS2 and when I use --dos and/or --dumpgrid, I get the following error:
 
```
ERROR
 exit code 4: symmetry error
 
 Unexpected tetrahedron weight
 
     occurs in file: type_qpointmesh_gridgeneration.f90
     occurs on line: 1283
        active rank: 3 out of 16
```
Here is the full command I am using:

`mpirun phonon_dispersion_relations -qg 16 16 16 --dos --unit thz -nq 100
`
Please find attached the infiles:
    - infile.forceconstants
    - infile.forceconstant_thirdorder
    - infile.forces
    - infile.meta
    - infile.positions
    - infile.ssposcar
    - infile.ucposcar
    - infile.stat
 and the log file I got from the execution of the program.

[files.zip](https://github.com/tdep-developers/tdep/files/15496024/files.zip)

If anyone could help with this it would really be helpful, thank you in advance.

**Comment by flokno** [comment]
It seems to work for odd numbers of qpoints (say 15x15x15), and without MPI. Can you confirm?

**Comment by chewingram** [comment]
> It seems to work for odd numbers of qpoints (say 15x15x15), and without MPI. Can you confirm?

Indeed on only 1 core it works fine; on multiple cores the odd number thing you suggest works, otherwise that error is raised.
A bit strange, do you have any idea of why this occur?

**Comment by flokno** [comment]
Not yet. Can you check if the result with and without MPI are identical? Same for odd/even grids (for sufficient grid density)

**Comment by chewingram** [comment]
> Not yet. Can you check if the result with and without MPI are identical? Same for odd/even grids (for sufficient grid density)

Done. I did serial & parallel with 5x5x5 and the results are identical (I checked eigenvalues and eigenvectors), and serial with 63x63x63 and 64x64x64 and again identical.

**Comment by flokno** [comment]
Thanks for checking! We'll keep the issue open as a reminder to look into this at some point

**Comment by flokno** [comment]
@chewingram can you check with the latest commit https://github.com/tdep-developers/tdep/commit/a470018662f4681bced5038d4f2e03f257e22898 ?

**Comment by chewingram** [comment]
Hi! I just tried on a 16x16x16 grid with 8 cores before and after pulling, and I confirm now it works.
Thanks!

**Comment by flokno** [comment]
Thanks for checking!
