### ISSUE TITLE
[ERROR] exit code 4: symmetry error. Could not locate tuplet

### ISSUE THREAD

**Issue by R3aptor** [tdep-developers/tdep#71]
I try to calculate the force constants for As2S3.
I run the command: extract_forceconstants -rc2 25 --polar > fc2_25_polar_log

The whole text of the error message I have got is:

 ERROR
 exit code 4: symmetry error
 Could not locate tuplet
     occurs in file: lo_symmetry_of_interactions_tuplets.f90
     occurs on line: 730
        active rank: 0 out of 1

(log file  and all input (infile.*) are also attached in the archive).

What is the reason of the problem? And how can I solve it?

[error_input.zip](https://github.com/user-attachments/files/15970244/error_input.zip)

**Comment by flokno** [comment]
Please check https://github.com/tdep-developers/tdep?tab=readme-ov-file#troubleshooting and https://github.com/tdep-developers/tdep-tutorials/tree/main/00_preparation/refine_symmetry
