### ISSUE TITLE
NO outfile.sqe.hdf5 output file

### ISSUE THREAD

**Issue by tingguangli** [tdep-developers/tdep#77]
When I run TDEP by the command:
mpirun -n 32 lineshape --path -qg 7 7 7 -ne 600 --temperature 300

I did not get the desired output files as in the manual:https://ollehellman.github.io/program/lineshape.html
I uploaded my inputfiles as well as output files (outfile.dispersion_relations.hdf5 is the only file that I got. and tdep.out is the file that I saved as a record of my simulation.)
Even I reduced my ucposcar from 64 atoms to 8 atoms, it still took me over 4 days to run the linshape calculation. Could you help me with why I could not get the sqe.hdf5 output file as stated in the manual? Thanks a lot!

Best Regards,
Tingguang
[TDEP_ERROR_report.zip](https://github.com/user-attachments/files/16150379/TDEP_ERROR_report.zip)

**Comment by flokno** [comment]
I cannot reproduce the error since the number of atoms in the unit cell and the force constants do not match.

As a general note: `lineshape` should run up to many 1000's of cores, I would expect you can cut your computation time at least by a factor of 100 this way. I.e. from 4 days to 1h.

**Comment by tingguangli** [comment]
[TDEP_ERROR_report.zip](https://github.com/user-attachments/files/16161689/TDEP_ERROR_report.zip)
Here is the correct infiles for forceconstants (8 atoms). Sorry about the mistake.
When you said run up to many 1000's of cores do you mean by mpirun n - 1000? I used mpirun - 32n already in computing cluster. Thanks a lot!

**Comment by tingguangli** [comment]
Yes, I did get this file, but I think based on the lineshape webpage, I should get a file outfile.sqe.hdf5 when I run on a specific path? (I assume that I use the default path will give me the same thing)
[infile_qpoints_dispersion.zip](https://github.com/user-attachments/files/16162095/infile_qpoints_dispersion.zip)

Also, when I tried read path function, the program always automatically recognize it as a single point calculation. (I uploaded my infile.qpoints_dispersion) here:

**Comment by flokno** [comment]
https://tdep-developers.github.io/tdep/program/lineshape/#outfilephonon_spectral_functionhdf5

You have to specify `lineshape --path --readpath`. In the current `main` version of TDEP, it should throw an error if you only specify `--readpath`

**Comment by tingguangli** [comment]
Here is what I got from the example in tdep website:
https://ollehellman.github.io/page/workflows/minimal_example_1.html

When running this command:
mpirun lineshape --path -qg 7 7 7 -ne 600 --temperature 800
will give a sqe file so that I can use similar method to plot the plots similar to that example?

**Comment by flokno** [comment]
You are looking at the legacy website. Admittedly, it looks very similar to the current one, which you find here: https://tdep-developers.github.io/tdep/

**Comment by tingguangli** [comment]
I have one more question: Now I successfully produce the plot: I check the website that you gave me and I did not find the default high symmetry path (I mean the q ticks) do you know where I can get the label of high symmetry points? Thanks a lot!

**Comment by flokno** [comment]
Is there not attribute `q_tick_labels` in the hdf5 file like in the snippets? https://tdep-developers.github.io/tdep/program/lineshape/#outfilephonon_spectral_functionhdf5
