### ISSUE TITLE
Compilation error in new TDEP version

### ISSUE THREAD

**Issue by mayankaditya** [tdep-developers/tdep#83]
Hi Florian Knoop,

I am trying to install the new TDEP version on my Ubuntu desktop 24.04 version with ifort compilers. But I am getting the following error.
![Screenshot from 2024-08-19 14-35-23](https://github.com/user-attachments/assets/62f7342a-2266-4265-8303-fcf7475d0f4f)
 Please advise.

ifort -fpp  -DGPx11 -Dclusterprogressbar  -L/opt/intel/oneapi/mkl/2023.1.0/lib/intel64 -L//home/mayank/SOFTWARE/hdf5-1.10.10/Mayank//lib  -L/opt/intel/oneapi/mpi/2021.9.0/lib -mkl=cluster -lhdf5 -lhdf5_fortran  -lmpi -lmpifort -I/opt/intel/oneapi/mkl/2023.1.0/include -I//home/mayank/SOFTWARE/hdf5-1.10.10/Mayank//include -I/opt/intel/oneapi/mkl/2023.1.0/include/fftw -I/opt/intel/oneapi/mpi/2021.9.0/include -module ../../inc/libolle/  -c type_symmetrylist_unique.f90 -o ../../build/libolle/type_symmetrylist_unique.o
ifort: command line remark #10412: option '-mkl=cluster' is deprecated and will be removed in a future release. Please use the replacement option '-qmkl=cluster'
type_symmetrylist_unique.f90(2225): error #6457: This derived type name has not been declared.   [LO_SPACEGROUP_OPERATION]
    type(lo_spacegroup_operation), intent(in) :: op
---------^
type_symmetrylist_unique.f90(2219): error #6404: This name does not have a type, and must have an explicit type.   [OP]
function stars_equal_after_operation(sl,p1,p2,op,s1,s2) result(match)
----------------------------------------------^
type_symmetrylist_unique.f90(2268): error #6362: The data types of the argument(s) are invalid.   [MATMUL]
        v0=matmul(op%m,s1%v(:,i))
------------------^
type_symmetrylist_unique.f90(2268): error #6361: An array-valued argument is required in this context.   [MATMUL]
        v0=matmul(op%m,s1%v(:,i))
------------------^
type_symmetrylist_unique.f90(2268): error #6241: The shapes of the arguments are inconsistent or nonconformable.   [MATMUL]
        v0=matmul(op%m,s1%v(:,i))
-----------^
compilation aborted for type_symmetrylist_unique.f90 (code 1)
make: *** [Makefile:732: ../../build/libolle/type_symmetrylist_unique.o] Error 1
make: *** Waiting for unfinished jobs....

Thanks,
Mayank

**Comment by flokno** [comment]
Did you try with gfortran?

**Comment by mayankaditya** [comment]
I tried with Gfortran. But getting another issue:

gfortran: error: unrecognized command line option ‘-fallow-argument-mismatch’; did you mean ‘-Wno-argument-mismatch’?

**Comment by flokno** [comment]
@mayankaditya I just noticed that the error was already fixed in the `main` brach in https://github.com/tdep-developers/tdep/pull/41

It is therefore also fixed in the newest release: https://github.com/tdep-developers/tdep/releases/tag/24.09

Thanks for using TDEP and reporting the bug!

**Comment by mayankaditya** [comment]
Thank you, Florian Knoop, for resolving the issue.

With regards,
Mayank
