### ISSUE TITLE
[ERROR] fatal error: 'CGAL/gmpq.h' file not found

### ISSUE THREAD

**Issue by LaiaJP** [tdep-developers/tdep#84]
Hello,

When compiling TDEP with CGAL, I encountered the following error:

```
cgal_chull3_intersection.cc:10:10: fatal error: 'CGAL/gmpq.h' file not found
   10 | #include <CGAL/gmpq.h>
      |          ^~~~~~~~~~~~~
```

I believe the header name is incorrect.

If I modify the `src/libolle/cgal_chull3_intersection.cc` file and use `#include <CGAL/Gmpq.h>`, it compiles perfectly.

I’ve checked with two CGAL versions (4.14.3 and 5.6.1), and in both versions, the header is named Gmpq.h instead of gmpq.h.

By the way, I'm compiling the TDEP from the main branch. I just ran `git clone https://github.com/tdep-developers/tdep.git`.

Thanks!

**Comment by flokno** [comment]
Hi, did you also try this branch? https://github.com/tdep-developers/tdep/pull/69

**Comment by LaiaJP** [comment]
Hello flokno,
I just tried it, and I got the same error:
cgal_chull3_intersection.cc:10:10: fatal error: 'CGAL/gmpq.h' file not found
   10 | #include <CGAL/gmpq.h>
      |          ^~~~~~~~~~~~~
1 error generated.

The issue persists because the header name still uses a lowercase letter instead of an uppercase one.
If I change it to uppercase, it compiles perfectly.

**Comment by flokno** [comment]
I confirm that the file name is correct. However, I did not get an error when compiling. Which compilers (`important_settings`) are you using?

I will include the change in https://github.com/tdep-developers/tdep/pull/69

**Comment by LaiaJP** [comment]
Here it is the important_settings file that I've used. I made it based on the examples that were provided in the github.
Is using intel, intel mpi, mkl, the fftw of mkl, hdf5, boost and cgal.
If you find something that can be improved, let me know :)
[important_settings.txt](https://github.com/user-attachments/files/16676490/important_settings.txt)

**Comment by flokno** [comment]
@LaiaJP can you confirm that https://github.com/tdep-developers/tdep/pull/69 compiles and works on your end?

**Comment by LaiaJP** [comment]
I just tried and it works perfectly. Thank you!

**Comment by flokno** [comment]
Great, thanks @LaiaJP !

I added some information on how to actually compile with CGAL here: https://github.com/tdep-developers/tdep/wiki/CGAL-support

Please let me know if you feel that something else could be mentioned or included
