### ISSUE TITLE
How to show more shells

### ISSUE THREAD

**Issue by Guodonglin-cqust** [tdep-developers/tdep#99]
N pair shells:          29
    shell:           1           1   0.0000000000000000     
    shell:           2           1   0.0000000000000000     
    shell:           3           3   0.0000000000000000     
    shell:           4          12   1.9479855477649999     
    shell:           5          24   2.7548675809560454     
    shell:           6          24   2.7548675809560454     
    shell:           7          16   3.3740099411388700     
    shell:           8          12   3.8959710955299998     
    shell:           9           6   3.8959710955299998     
    shell:          10           6   3.8959710955299998     
    shell:          11           6   3.8959710955299998     
    shell:          12          48   4.3558281039897038     
    shell:          13          48   4.7715706183402382     
    shell:          14          48   4.7715706183402382     
    shell:          15          12   5.5097351619120909     
    shell:          16          24   5.5097351619120909     
    shell:          17          12   5.5097351619120909     
    shell:          18          12   5.5097351619120909     
    shell:          19          48   5.8439566432949999     
    shell:          20          12   5.8439566432949999     
     ... and 9 more shells
 ... determined singlet nullspace
 ... determined pair nullspace
 ... determined dielectric tensor nullspace

How to show more shells, i want to know the cutoff, thank you very much.

Best wishes

Donglin guo

**Comment by flokno** [comment]
The cutoff is written at the very top, e.g.,

```
 READ STRUCTURE AND SETUP CUTOFFS
 ... reading unitcell
 ... min cutoff:       3.14993
 ... max cutoff:       9.95139
 --> rc2 cutoff:      10.00000
 --> rc3 cutoff:      -1.00000
 --> rc4 cutoff:      -1.00000
```

To get all the pair shells, I recommend to use the script https://github.com/flokno/tools.tdep/blob/main/tdeptools/scripts/ase_get_distance_table.py from `tdeptools`.

When you run

```
ase_get_distance_table infile.ssposcar
```

you will get all pair shells including the elements in a csv file.

Does that solve the issue?

**Comment by Guodonglin-cqust** [comment]
Read `infile.ssposcar`
... autodetect format `vasp` for infile.ssposcar
... material: Atoms(symbols='O192Sr64Ti64', pbc=True, cell=[15.58388438212, 15.58388438212, 15.58388438212])
... MIC:                         True
... density (atoms/AA**3):      0.085
--> atom volume (AA**3):       11.827
--> atom radius (AA):           1.413
--> atoms per  1A sphere:       0.354
--> atoms per  3A sphere:       9.563
--> atoms per  4A sphere:      22.667
--> atoms per  5A sphere:      44.271
--> atoms per 10A sphere:     354.170
... use 1 replicas to see more neighbors
... number of atoms: 320
... unique pairs: ['O-Ti' 'O-Sr' 'O-O' 'Sr-Ti' 'Sr-Sr' 'Ti-Ti']
... first 15 neighbors, first is nearest neighbor:
      symbols  distances
0        O-Ti    1.94799
768      O-Sr    2.75487
3840    Sr-Ti    3.37401
4864    Sr-Sr    3.89597
6784     O-Ti    4.35583
9856      O-O    4.77157
16000   Sr-Sr    5.50974
19840    O-Ti    5.84396
23680    O-Sr    6.16007
29824   Sr-Ti    6.46074
32896     O-O    6.74802
35456    O-Ti    7.02356
38528    O-Sr    7.28869
50816     O-O    7.79194
51776    O-Ti    8.03175
... save to 'outfile.distances.csv'
... save unique distances to 'outfile.distances_unique.csv'

yes, it solves my problem, thank you very much.

**Comment by flokno** [comment]
Great, thank you and happy computing!
